### ISSUE TITLE
咨询一下，客户端怎么验证access_token的有效性？

### ISSUE THREAD

**Issue by ancon** [jobmission/oauth2-resource#1]
server端关了，resource端的token仍然有效？怎么做到验证呢？

**Comment by jobmission** [comment]
不好意思，最近处理其他项目没有看到。resource端会在第一次验证token的时候会把server端Jwt签名的公钥缓存下来，以后就不用再和server端通信就可以完成本地验证了。

**Comment by jobmission** [comment]
还有其他疑问吗？
